version: "3"

services: 
  traefik:
    image: traefik:1.3.6-alpine
    restart: always
    labels: 
      - traefik.frontend.rule=Host:monitor.shapaozi.local
      - traefik.port=8080
    ports: 
      - 80:80
      - 443:443
    networks:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - $PWD/traefik.toml:/traefik.toml
      - $PWD/acme.json:/acme.json
    container_name: traefik

networks: 
  proxy:
    external: true