defaultEntryPoints = ["http", "https"]

[web]

address = ":8080"
  [web.auth.basic]
<<<<<<< HEAD
    users = ["admin:$apr1$2Eo9RawW$GrisxwNdt7v6J76sm.bTb."]
=======
    users = ["admin:$apr1$2Eo9RawW$GrisxwNdt7v6J76sm.bTb"]
>>>>>>> 1f5a9a93fae034a8238d6debdf2e58317409140d

[entryPoints]
  [entryPoints.http]
  address = ":80"
#    [entryPoints.http.redirect]
#      entryPoint = "https
  [entryPoints.https]
  address = ":443"
    [entryPoints.https.tls]

[acme]
email = "hugo_zang@icloud.com"
entryPoint = "https"
storage = "acme.json"
onHostRule = true
onDemand = false